### ISSUE TITLE
Porting/AArch64 is outdated

### ISSUE THREAD

**Issue by neuschaefer** [somasis/musl-wiki#15]
Hi,

I noticed that the Porting/AArch64 page is now out of date, because the aarch64 port is merged upstream and stable enough that Alpine Linux builds binary packages for it.

Thanks for maintaining this useful wiki.

**Comment by richfelker** [comment]
This seems to have been fixed by https://github.com/somasis/musl-wiki/commit/b24de5cee87731279f4d0acc0e47f68227c088f0
