### ISSUE TITLE
Generating reference value for mathematical functions

### ISSUE THREAD

**Issue by nikola-suljagic** [somasis/musl-wiki#35]
Hello, can we  tell me, how the reference value is generating for math functions (for example reference value in acos.h)?
And is there any tool for generating accurate reference value for math function in some  range? 
Thank in advance,
Nikola

**Comment by somasis** [comment]
Hey, sorry for the slow response. If you're still waiting on a response though, this seems more appropriate for [the mailing list](http://musl.libc.org/support.html) though, if you could send it there instead.
