### ISSUE TITLE
Gentoo musl stages no longer 'experimental'

### ISSUE THREAD

**Issue by mjeveritt** [somasis/musl-wiki#64]
Under https://wiki.musl-libc.org/projects-using-musl.html#Linux-distros-shipping-musl-as-an-optional-package the musl stage3s are linked to the 'experimental' subsection of distfiles.gentoo.org . For a few months now, these have been migrated to the standard locations under 'releases' (eg. for x86_64 "amd64" in <gentoo mirror>/releases/amd64/autobuilds/current-stage3-amd64-openrc/).

See lower section of https://www.gentoo.org/downloads/ for further details.

**Comment by rofl0r** [comment]
if you're interested in having this fixed, why not provide a PR ?
